### PR TITLE
LPS-60246

### PR DESCRIPTION
**Pull request by daledotshan**

### CODE REVIEW

**Comment by daledotshan** [comment]
information from Hai:
When use title as urlTitle and urlTitle is existed in database, if validated(urlTitle + suffix).length <= the urlTitle field defination length, we use "title +suffix" as default urltitle. If validated(urlTitle + suffix).length > the urlTitle field defination length, we use substring() to cut the urlTitle.

**Comment by hhuijser** [comment]
@yuhai @daledotshan 

Couple of things:
1. The use of "prefix" is not really correct. It's not a prefix, so let's rename...
2. Line 1712 and 1739 are redundant.
3. Did you test this? From looking at this, I think it will break when urlTitle is exactly 75 chars?

suffix = "-1" --> suffix.length() = 2
urtTitle = "blah..." --> suffix.length() = 75

which means it will go to line 1712-1717 and on line 1714-1715, we get:
prefix = uniqueUrlTitle.substring(0, 75 - 2), which results in a string that is 74 chars.

Line 1717 -> prefix + suffix = 74 + 2 = 76 chars --> too long

**Comment by hhuijser** [comment]
Sorry, my third point is not right. Your logic is working fine...

**Comment by hhuijser** [comment]
I'll take are of 1 and 2

**Comment by yuhai** [comment]
thanks, Hugo. :)

**Comment by hhuijser** [comment]
Hey @yuhai 

I simplified your fix a little, but didn't test. Can you test?
Sent to Adolfo for review already: https://github.com/adolfopa/liferay-plugins/pull/34

**Comment by yuhai** [comment]
yes, I will test your change and let you know.

**Comment by yuhai** [comment]
Hi Hugo,

Your changes work for me.

Thanks,
Hai

**Pull request closed without merging**
