### PR TITLE
LPS-60246

### PR DESCRIPTION
**Pull request by daledotshan**

### CODE REVIEW

**Comment by daledotshan** [comment]
Information from Hai:

Please refer to https://issues.liferay.com/browse/LPS-60246 description to know the issue.

In KBarticle, we allow to enter same KBArticle as title and it is the same as web content,
The fix refers to JournalArticleLocalServiceImpl.getUniqueUrlTitle(long groupId, String articleId, String urlTitle), the fix can avoid the data length exceed KBArticle's urlTitle field design(75). Actually, the case also occur in the below cases:

Case 1. When add two KBArticles title are different and urltitle is empty. For example:
Article1: Title: 75charctersYUHAI, urltitle:empty.
Article2: Title: 75charctersYU, urltitle:empty.

When save Article1, urltitle will be "75charcters" , "YUHAI" will be removed. It can add successful.
When save Article2, urltitle will be "75charcters+1" , The issue will occur. KBArticle's urlTitle will exceed the field's design(75)

Case 2. For previous released low version 2.0.1 KB, we didn't have urltitle field. When upgrade from 2.0.1 to 2.1.0, we added urltitle field. In upgrade process, we didn't handle urltitle field to add title as urltitle by default. Please refer to https://issues.liferay.com/browse/LPS-45403?focusedCommentId=468076&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-468076.

So for old datas which created in 2.0.1, when export them, their urltitle will be empty. And they will use title as urltitle when import them. The same case might occur as the case 1 mentioned.

In addition, for when we enter urlTitle in UI, its content have cut to 75. Front code has control this. And in java, JournalArticleLocalServiceImpl.validateUrlTitle() will handle urltitle(isnoutnull) case. So we only consider when enter title exceed 75 and urlTitle is empty in UI. At this case, urlTitle is generated by title by default.

**Comment by hhuijser** [comment]
@yuhai @daledotshan 

This doesn't seem right, if we we already have urlTitle = "test" and test-1 is already being used, we'll get test-1-2 (instead of test-2)

**Comment by hhuijser** [comment]
Hmm, I see that my statement is not true, because of your if statement there.
Looking at it more

**Comment by hhuijser** [comment]
Okay, still not sure if this is right.... I can see how we want to do this when we have long titles that go over 75 characters.
However, if we have a short title (like "test") it will also result in something like "te-2", which does not seem to make sense?

**Comment by daledotshan** [comment]
yeah, add a url length validation is better

**Comment by hhuijser** [comment]
Okay, will close this for now

**Pull request closed without merging**
