### PR TITLE
LPS-45034

### PR DESCRIPTION
**Pull request by yuhai**
Hi Hugo,

The pull request extends from https://github.com/hhuijser/liferay-plugins/pull/171

We discussed the issue with Ray by email. At that time, Ray was busy and he let me discussed the issue with workflow team. You can find the title "Reagrding LPS-45034 API:WorkflowTaskManagerUtil.getWorkflowTasksBySubmittingUser() returns no rows
" in email.

Thanks,
Hai

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey Hai,

I remember the discussion we had about this.
In the email thread, Ray told us to submit this to the workflow team.
You mention that you discussed this with the workflow team? I don't see any documentation regarding this?

**Comment by yuhai** [comment]
Hi Hugo,

Sorry, I didn't submit this to the workflow team. Should we submit the pull request to workflow team or I post one thread on our forum or discuss the issue with workflow team by email?

Thanks,
Hai

**Comment by hhuijser** [comment]
I will send the pull to Marcellus. You can post some more info on the pull or LPS

**Comment by yuhai** [comment]
Update some explataion on LPS. Thanks.

**Comment by hhuijser** [comment]
Sent to Marcellus for review: https://github.com/marcellustavares/liferay-plugins/pull/298

**Pull request closed without merging**
